{{- if not .Values.persistence.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
  labels: {app.kubernetes.io/instance: {{ .Release.Name | quote }}}
  {{- if .Values.persistence.keep }}
  annotations: {helm.sh/resource-policy: keep}
  {{- end }}
spec:
  accessModes: {{ .Values.persistence.accessModes | toJson }}
  {{- if ne .Values.persistence.storageClass nil }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
